### ISSUE TITLE
Omnisearch is not hidden in fullscreen

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-fullscreen#1]
The Omnisearch is not hidden in fullscreen. It is still visible.

**Comment by PaulaScharf** [comment]
This is intended. Bundles that are shown on top of the map should still be visible in fullscreen. This is analog to the fullscreen functionality provided by esri ([see](https://developers.arcgis.com/javascript/latest/sample-code/visualization-vv-color-animate/)).

However if there is great need for this feature, then I would like to know if only the searchbar from omnisearch needs to be hidden or also other/all tools on the map.

**Comment by gadgec** [comment]
In fullscreen mode there is no tool functionality (i.e. toolsets on top of the map), so visible tools may mislead the users.

**Comment by sholtkamp** [comment]
Issue already fixed in [commit ce2b14c6600fbe7c238962915602ed258101a9f7](https://github.com/conterra/mapapps-fullscreen/commit/ce2b14c6600fbe7c238962915602ed258101a9f7)
